biblioteca-config:
  liberado: false

server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecospring_biblioteca-prod?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      javax:
        persistence:
          ddl-auto: none
    open-in-view: true
    generate-ddl: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # resolvendo incomppatibilidade entre o springfox e o spring boot
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
      - classpath:db/tetdata
    # table: MigrationHistory
    # default-schema: imomo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
